### ISSUE TITLE
Error parsing filter on every request

### ISSUE THREAD

**Issue by Ewocker** [TryGhost/Ruby#5]
Might be related to this https://forum.ghost.org/t/problem-with-filter-by-tags/13262

```
[2020-11-21 12:05:33] ERROR Error parsing filter

Error parsing filter

Error ID:
    db82fec0-2bf1-11eb-9df8-5f80a57020bd

----------------------------------------

BadRequestError: Error parsing filter
    at new BadRequestError (/var/lib/ghost/versions/3.38.2/node_modules/ghost-ignition/lib/errors/index.js:113:23)
    at Child.applyDefaultAndCustomFilters (/var/lib/ghost/versions/3.38.2/core/server/models/plugins/filter.js:122:23)
    at Function.getFilteredCollection (/var/lib/ghost/versions/3.38.2/core/server/models/base/index.js:850:28)
    at Function.findPage (/var/lib/ghost/versions/3.38.2/core/server/models/base/index.js:926:37)
    at Object.query (/var/lib/ghost/versions/3.38.2/core/server/api/canary/posts-public.js:33:32)
    at Object.query (/var/lib/ghost/versions/3.38.2/core/server/api/shared/pipeline.js:156:24)
    at /var/lib/ghost/versions/3.38.2/core/server/api/shared/pipeline.js:243:35
    at tryCatcher (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/async.js:15:14)

Error: Query Error: unexpected character in filter at char 7
(tags:[]+id:-)+type:post
-------^
Expecting 'NULL', 'TRUE', 'FALSE', 'NUMBER', 'LITERAL', 'STRING', got 'RBRACKET'
    at Parser.parser.parseError (/var/lib/ghost/versions/3.38.2/node_modules/@nexes/nql-lang/dist/parser.js:328:12)
    at Parser.parse (/var/lib/ghost/versions/3.38.2/node_modules/@nexes/nql-lang/dist/parser.js:245:22)
    at Object.exports.parse (/var/lib/ghost/versions/3.38.2/node_modules/@nexes/nql-lang/lib/nql.js:18:44)
    at Object.api.parse (/var/lib/ghost/versions/3.38.2/node_modules/@nexes/nql/lib/nql.js:15:31)
    at Object.api.querySQL (/var/lib/ghost/versions/3.38.2/node_modules/@nexes/nql/lib/nql.js:49:44)
    at Builder.<anonymous> (/var/lib/ghost/versions/3.38.2/core/server/models/plugins/filter.js:119:24)
    at Object.query (/var/lib/ghost/versions/3.38.2/node_modules/bookshelf/lib/helpers.js:57:14)
    at Child.query (/var/lib/ghost/versions/3.38.2/node_modules/bookshelf/lib/model.js:1256:22)
    at Child.applyDefaultAndCustomFilters (/var/lib/ghost/versions/3.38.2/core/server/models/plugins/filter.js:112:22)
    at Function.getFilteredCollection (/var/lib/ghost/versions/3.38.2/core/server/models/base/index.js:850:28)
    at Function.findPage (/var/lib/ghost/versions/3.38.2/core/server/models/base/index.js:926:37)
    at Object.query (/var/lib/ghost/versions/3.38.2/core/server/api/canary/posts-public.js:33:32)
    at Object.query (/var/lib/ghost/versions/3.38.2/core/server/api/shared/pipeline.js:156:24)
    at /var/lib/ghost/versions/3.38.2/core/server/api/shared/pipeline.js:243:35
    at tryCatcher (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/3.38.2/node_modules/bluebird/js/release/promise.js:547:31)
```

**Comment by minimaluminium** [comment]
Could't reproduce the issue, and closing due to inactivity.
